### ISSUE TITLE
در ستایش ساخت کانکشن

### ISSUE THREAD

**Issue by maretaf** [AliJavidiCS/Wish_I_knew_Eearlier#4]
چیزی که خیلی پررنگه، درس خوندنه. که آره بخونید خیلی مهمه ولی یه چیز مهم‌تر رو یادتون نره؛ یونیک‌ترین ارزشی که درحال حاضر دانشگاه می‌تونه به دانش‌جوش ارائه بده ساخت ارتباطات و کانکشنه. اگر قرار به درس خوندن و یاد گرفتن باشه که خیلی از استادها اصلا سواد درس دادن ندارن((: و عملا درس رو با یوتیوب و سایت‌هایی مثل فرادرس می‌تونید یاد بگیرید. تمرین‌هاتون هم با عمو چت بزنید((: از اون طرف اگر قصدتون ورود به بازار کار باشه الان مدرک کم‌ترین اهمیت رو داره. و حتی اگر قصد مهاجرت تحصیلی هم دارین باز ساخت ارتباط و کانکشن بیش‌ترین چیزیه که به کارتون می‌آد. به‌خصوص وقتی نیاز به توصیه‌نامه داشته باشین. 

مورد بعدی دربارۀ رزومه، مشیا نوشته بود که شده یه ورد باز کنید و فقط اسم و فامیل‌تون رو بنویسید. پیشنهاد خوبیه ولی الان ان‌قدر ابزار هست که می‌شه به راحتی رزومه ساخت که در حق خودتون ظلم کردین اگر استفاده نکنین. پیشنهادم بین سایت‌های ایرانی سایت «**کاربوم**»ه. هر درسی که گذرونیدن یا زبان جدیدی یاد گرفتین یا با یه نرم‌افزار جدید یاد گرفتین به رزومه‌تون اضافه کنید و یه درجه‌ای بهش بدین. مزیتش اینه بعد از یه مدت می‌فهمین که دقیقاً چه‌کار کردین توی دانشگاه و می‌تونین تصمیم بگیرین که می‌خواین توی کدوم حوزه عمیق‌تر بشین؟

از طرف دیگه حتماً حتماً **لینکدین** نصب کنین و به مرور پروفایل‌تون رو کامل کنید. چیزی که باید حتماً حواس‌تون بهش باشه اینه که عکس پروفایل‌تون نه خیلی رسمی مثل عکس ۴×۳ باشه نه عکس سلفی مناسب شیر کردن توی اینستاگرام. تحصیلات‌تون رو وارد کنید، کم‌کم استادها رو پیدا کنین و کانکشن بسازین با هم‌دانشگاهی‌ها و غیر هم‌دانشگاهی‌هاتون. اگر قصدتون مهاجرته هم برای توصیه‌نامه و پیدا کردن دانشگاه بعداً خیلی کمک‌تون می‌کنه. اگر قصدتون ورود به بازار کاره هم که درست‌ترین جای ممکن اومدین. 

اگر توی این موارد سوالی داشتین هم خوش‌حال می‌شم کمک‌تون کنم ولی در اولین قدم برین لینکدین نصب کنید((:

**Comment by AliJavidiCS** [comment]
یه کم مرتبش کردم و یه کم هرسش کردم. ممنون ازت. اضافه شد!
